"""Recreate schema

Revision ID: 04d474da3a87
Revises: 
Create Date: 2025-04-23 17:38:05.680262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d474da3a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_result_id', sa.Integer(), nullable=False),
    sa.Column('original_charge', sa.String(length=200), nullable=True),
    sa.Column('amended_charge', sa.String(length=200), nullable=True),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('jail_time_imposed', sa.String(length=50), nullable=True),
    sa.Column('jail_time_suspended', sa.String(length=50), nullable=True),
    sa.Column('fine_imposed', sa.String(length=50), nullable=True),
    sa.Column('fine_suspended', sa.String(length=50), nullable=True),
    sa.Column('license_suspension', sa.String(length=100), nullable=True),
    sa.Column('restricted_license', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_result_id'], ['case_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probation_term', sa.String(length=50), nullable=True))

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_waiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('absence_waiver')

    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('probation_term')

    op.drop_table('charge')
    # ### end Alembic commands ###
