"""Initial migration

Revision ID: 12953fd2aa77
Revises: 
Create Date: 2025-04-30 15:35:16.808745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12953fd2aa77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defendant_name', sa.String(length=120), nullable=True),
    sa.Column('offense', sa.String(length=200), nullable=True),
    sa.Column('amended_charge', sa.String(length=200), nullable=True),
    sa.Column('disposition', sa.String(length=200), nullable=True),
    sa.Column('other_disposition', sa.String(length=200), nullable=True),
    sa.Column('jail_time_imposed', sa.String(length=50), nullable=True),
    sa.Column('jail_time_suspended', sa.String(length=50), nullable=True),
    sa.Column('fine_imposed', sa.String(length=50), nullable=True),
    sa.Column('fine_suspended', sa.String(length=50), nullable=True),
    sa.Column('license_suspension', sa.String(length=100), nullable=True),
    sa.Column('asap_ordered', sa.String(length=10), nullable=True),
    sa.Column('probation_type', sa.String(length=50), nullable=True),
    sa.Column('probation_term', sa.String(length=50), nullable=True),
    sa.Column('was_continued', sa.String(length=10), nullable=True),
    sa.Column('continuation_date', sa.String(length=20), nullable=True),
    sa.Column('client_email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_disposition', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('send_review_links', sa.Boolean(), nullable=True),
    sa.Column('license_suspension_term', sa.String(length=100), nullable=True),
    sa.Column('restricted_license_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clio_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('court_date', sa.String(length=20), nullable=True),
    sa.Column('court_time', sa.String(length=20), nullable=True),
    sa.Column('court', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('facts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('send_retainer', sa.Boolean(), nullable=True),
    sa.Column('retainer_amount', sa.String(length=50), nullable=True),
    sa.Column('lvm', sa.Boolean(), nullable=True),
    sa.Column('not_pc', sa.Boolean(), nullable=True),
    sa.Column('quote', sa.String(length=50), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('custom_source', sa.String(length=100), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('charges', sa.Text(), nullable=True),
    sa.Column('staff_member', sa.String(length=100), nullable=True),
    sa.Column('absence_waiver', sa.Boolean(), nullable=True),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('homework_driving_record', sa.Boolean(), nullable=True),
    sa.Column('homework_reckless_program', sa.Boolean(), nullable=True),
    sa.Column('homework_driver_improvement', sa.Boolean(), nullable=True),
    sa.Column('homework_speedometer', sa.Boolean(), nullable=True),
    sa.Column('homework_community_service', sa.Boolean(), nullable=True),
    sa.Column('homework_community_service_hours', sa.String(length=20), nullable=True),
    sa.Column('homework_substance_evaluation', sa.Boolean(), nullable=True),
    sa.Column('homework_asap', sa.Boolean(), nullable=True),
    sa.Column('homework_shoplifting', sa.Boolean(), nullable=True),
    sa.Column('homework_medical_conditions', sa.Boolean(), nullable=True),
    sa.Column('homework_photos', sa.Boolean(), nullable=True),
    sa.Column('homework_shoplifting_program', sa.Boolean(), nullable=True),
    sa.Column('homework_military_awards', sa.Boolean(), nullable=True),
    sa.Column('homework_dd214', sa.Boolean(), nullable=True),
    sa.Column('homework_community_involvement', sa.Boolean(), nullable=True),
    sa.Column('homework_anger_management_courseforcourt', sa.Boolean(), nullable=True),
    sa.Column('homework_vasap', sa.Boolean(), nullable=True),
    sa.Column('homework_substance_abuse_treatment', sa.Boolean(), nullable=True),
    sa.Column('homework_substance_abuse_counseling', sa.Boolean(), nullable=True),
    sa.Column('homework_transcripts', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_result_id', sa.Integer(), nullable=False),
    sa.Column('original_charge', sa.String(length=200), nullable=True),
    sa.Column('amended_charge', sa.String(length=200), nullable=True),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('jail_time_imposed', sa.String(length=50), nullable=True),
    sa.Column('jail_time_suspended', sa.String(length=50), nullable=True),
    sa.Column('fine_imposed', sa.String(length=50), nullable=True),
    sa.Column('fine_suspended', sa.String(length=50), nullable=True),
    sa.Column('license_suspension', sa.String(length=100), nullable=True),
    sa.Column('restricted_license', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_result_id'], ['case_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge')
    op.drop_table('lead')
    op.drop_table('clio_tokens')
    op.drop_table('case_result')
    # ### end Alembic commands ###
