"""empty message

Revision ID: 48391adcbe9c
Revises: 7fcec50fb3f1
Create Date: 2025-05-21 05:21:07.926935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48391adcbe9c'
down_revision = '7fcec50fb3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clio_contact')
    op.drop_table('clio_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clio_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clio_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clio_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clio_id')
    )
    # ### end Alembic commands ###
