"""Sync DB with Lead model updates

Revision ID: 5e2a780b0616
Revises: aaab9bc427e7
Create Date: 2025-05-02 08:36:53.262114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2a780b0616'
down_revision = 'aaab9bc427e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clio_matter_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('clio_matter_id')

    # ### end Alembic commands ###
