"""Add jail_time unit fields to Charge model

Revision ID: 6c277b895d00
Revises: c5bb58ca899e
Create Date: 2025-05-20 05:37:26.002676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c277b895d00'
down_revision = 'c5bb58ca899e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plea', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disposition_paragraph', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('jail_time_imposed_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('jail_time_suspended_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('license_suspension_term', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('restricted_license_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('probation_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('probation_term', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vasap', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('vip', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('community_service', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('anger_management', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('asap_ordered', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('charge_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bip_adapt', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sa_eval', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mh_eval', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_column('mh_eval')
        batch_op.drop_column('sa_eval')
        batch_op.drop_column('bip_adapt')
        batch_op.drop_column('charge_notes')
        batch_op.drop_column('asap_ordered')
        batch_op.drop_column('anger_management')
        batch_op.drop_column('community_service')
        batch_op.drop_column('vip')
        batch_op.drop_column('vasap')
        batch_op.drop_column('probation_term')
        batch_op.drop_column('probation_type')
        batch_op.drop_column('restricted_license_type')
        batch_op.drop_column('license_suspension_term')
        batch_op.drop_column('jail_time_suspended_unit')
        batch_op.drop_column('jail_time_imposed_unit')
        batch_op.drop_column('disposition_paragraph')
        batch_op.drop_column('plea')

    # ### end Alembic commands ###
