"""Force detect ClioContact

Revision ID: 7fcec50fb3f1
Revises: 9954edd40664
Create Date: 2025-05-21 04:58:25.733838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcec50fb3f1'
down_revision = '9954edd40664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clio_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clio_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clio_contact')
    # ### end Alembic commands ###
