"""Add ClioToken model

Revision ID: 92be62d5227c
Revises: 48391adcbe9c
Create Date: 2025-05-21 06:01:09.887256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92be62d5227c'
down_revision = '48391adcbe9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clio_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clio_token')
    # ### end Alembic commands ###
