"""Add matter fields to CaseResult

Revision ID: 9386c7ae856a
Revises: 92be62d5227c
Create Date: 2025-05-30 05:01:48.163894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9386c7ae856a'
down_revision = '92be62d5227c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matter_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('matter_display_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('matter_maildrop_address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('matter_maildrop_address')
        batch_op.drop_column('matter_display_number')
        batch_op.drop_column('matter_description')

    # ### end Alembic commands ###
