"""Add community_service_hours to Charge

Revision ID: 9954edd40664
Revises: 6c277b895d00
Create Date: 2025-05-20 05:44:37.234934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9954edd40664'
down_revision = '6c277b895d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_service_hours', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_column('community_service_hours')

    # ### end Alembic commands ###
