"""Your message here

Revision ID: aaab9bc427e7
Revises: 12953fd2aa77
Create Date: 2025-05-02 08:07:13.410465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaab9bc427e7'
down_revision = '12953fd2aa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attorney', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('calling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('homework_additional', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('homework_additional_notes', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('homework_no_hw', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('homework_no_hw')
        batch_op.drop_column('homework_additional_notes')
        batch_op.drop_column('homework_additional')
        batch_op.drop_column('calling')
        batch_op.drop_column('attorney')

    # ### end Alembic commands ###
