"""Add full charge-level fields to Charge model

Revision ID: c5bb58ca899e
Revises: f244510a4d06
Create Date: 2025-05-19 14:18:25.546198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bb58ca899e'
down_revision = 'f244510a4d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plea_offer', sa.Text(), nullable=True))

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calling_back', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plea_offer', sa.Text(), nullable=True))
        batch_op.drop_column('custom_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_source', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('plea_offer')
        batch_op.drop_column('calling_back')

    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('plea_offer')

    # ### end Alembic commands ###
