"""Initial migration

Revision ID: ebacc948ffd5
Revises: 
Create Date: 2025-04-23 17:01:18.885626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebacc948ffd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probation_term', sa.String(length=50), nullable=True))

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_waiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('absence_waiver')

    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('probation_term')

    # ### end Alembic commands ###
