"""Add clio_contact_id to CaseResult

Revision ID: f244510a4d06
Revises: 5e2a780b0616
Create Date: 2025-05-04 18:49:40.598627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f244510a4d06'
down_revision = '5e2a780b0616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clio_contact_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_result', schema=None) as batch_op:
        batch_op.drop_column('clio_contact_id')

    # ### end Alembic commands ###
